### PR TITLE
feat: update supabase types

### PR DESCRIPTION
**Pull request by altaywtf**
- updates types to match latest schema
- saves generated types as `database-generated`
- creates a utility to extract supbase tables conveniently: `Table<'account'>` for example 👍 : https://supabase.com/docs/guides/api/rest/generating-types#type-shorthands
- installs supabase as a dev dependency, this allows us to local installation instead of global supabase cli. also ensures that we're on the same version 👍 
- adds `.eslintignore` to ignore `types` folder

### CODE REVIEW

**Comment by altaywtf** [comment]
Current dependencies on/for this PR:
* main
  * **PR #12** <a href="https://app.graphite.dev/github/pr/experiment-station/beecast/12?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/experiment-station/beecast/12?utm_source=stack-comment).

**Comment by altaywtf** [comment]
we may also consider updating them on schedule as suggested here: https://supabase.com/docs/guides/api/rest/generating-types#update-types-automatically-with-github-actions

🥴 meh, maybe later™️

**Comment by okanisildar** [comment]
I had to update the account table based on the needs while I was developing can you re-generate the types for DB?

**Comment by altaywtf** [comment]
> I had to update the account table based on the needs while I was developing can you re-generate the types for DB?

@okanisildar done 👍

**Review by okanisildar — APPROVED** [review]

**Pull request merged**
