### PR TITLE
refactor: update `service/ai` params

### PR DESCRIPTION
**Pull request by altaywtf**

### CODE REVIEW

**Comment by altaywtf** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #56** <a href="https://app.graphite.dev/github/pr/experiment-station/beecast/56?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #57** <a href="https://app.graphite.dev/github/pr/experiment-station/beecast/57?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #59** <a href="https://app.graphite.dev/github/pr/experiment-station/beecast/59?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #61** <a href="https://app.graphite.dev/github/pr/experiment-station/beecast/61?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #62** <a href="https://app.graphite.dev/github/pr/experiment-station/beecast/62?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
            * **PR #60** <a href="https://app.graphite.dev/github/pr/experiment-station/beecast/60?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #58** <a href="https://app.graphite.dev/github/pr/experiment-station/beecast/58?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/experiment-station/beecast/62?utm_source=stack-comment).

**Review by okanisildar — APPROVED** [review]
Did you keep console.logs on purpose?

**Comment by altaywtf** [comment]
> Did you keep console.logs on purpose?

yeah, they're gone in the next one

**Comment by altaywtf** [comment]
### Merge activity

* **Dec 15, 10:33 AM**: @@altaywtf started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/experiment-station/beecast/62).

**Pull request merged**
